CORENAME ?= hatarib
platform ?= invalid
COREFILE ?= $(CORENAME)_libretro
CORESTATIC ?= $(CORENAME)_libretro_$(platform)
CORESTATIC_SUFFIX ?= .a
MAKEACTION ?= core
MAKEEXTRA ?=
CMAKEFLAGS_EXTRA ?=

ifeq ($(platform),win64)                        # windows-x64-mingw
	CMAKEFLAGS_EXTRA := -DCMAKE_SYSTEM_NAME=Windows
	MAKEEXTRA := SO_SUFFIX=.dll
else ifeq ($(platform),win32)                   # windows-i686-mingw
	CMAKEFLAGS_EXTRA := -DCMAKE_SYSTEM_NAME=Windows
	MAKEEXTRA := SO_SUFFIX=.dll
else ifeq ($(platform),unix)
ifneq ($(ARCH),x86)                             # linux-x64, linux-aarch64
else                                            # linux-i686
endif
else ifeq ($(platform),osx)
ifneq ($(ARCH),arm)                             # osx-x64
else                                            # osx-arm64
endif
else ifeq ($(ANDROID_PLATFORM),android-arm)     # android-make: android-arm
	CMAKEFLAGS_EXTRA := -DCMAKE_TOOLCHAIN_FILE=$(NDK_ROOT)/build/cmake/android.toolchain.cmake
	COREFILE := $(CORENAME)_libretro_android
else ifeq ($(ANDROID_PLATFORM),android-arm64)   # android-make: android-arm64
	CMAKEFLAGS_EXTRA := -DCMAKE_TOOLCHAIN_FILE=$(NDK_ROOT)/build/cmake/android.toolchain.cmake
	COREFILE := $(CORENAME)_libretro_android
else ifeq ($(ANDROID_PLATFORM),android-x86)     # android-make: android-x86
	CMAKEFLAGS_EXTRA := -DCMAKE_TOOLCHAIN_FILE=$(NDK_ROOT)/build/cmake/android.toolchain.cmake
	COREFILE := $(CORENAME)_libretro_android
else ifeq ($(ANDROID_PLATFORM),android-x86_64)  # android-make: android-x86_64
	CMAKEFLAGS_EXTRA := -DCMAKE_TOOLCHAIN_FILE=$(NDK_ROOT)/build/cmake/android.toolchain.cmake
	COREFILE := $(CORENAME)_libretro_android
else ifeq ($(platform),ios-arm64)               # ios-arm64
	COREFILE := $(CORENAME)_libretro_ios
else ifeq ($(platform),ios9)                    # ios9
	COREFILE := $(CORENAME)_libretro_ios
else ifeq ($(platform),tvos-arm64)              # tvos-arm64
	COREFILE := $(CORENAME)_libretro_tvos
else ifeq ($(platform),ps2)                     # ps2-static
	MAKEACTION := static
else ifeq ($(platform),psl1ght)                 # psl1ght-static
	MAKEACTION := static
else ifeq ($(platform),psp1)                    # psp-static
	MAKEACTION := static
else ifeq ($(platform),vita)                    # vita-static
	MAKEACTION := static
else ifeq ($(platform),ctr)                     # ctr-static
	CMAKEFLAGS_EXTRA := -DCMAKE_TOOLCHAIN_FILE=$(DEVKITPRO)/cmake/3DS.cmake
	MAKEACTION := static
else ifeq ($(platform),ngc)                     # ngc-static
	CMAKEFLAGS_EXTRA := -DCMAKE_TOOLCHAIN_FILE=$(DEVKITPRO)/cmake/GameCube.cmake
	MAKEACTION := static
else ifeq ($(platform),wii)                     # wii-static
	CMAKEFLAGS_EXTRA := -DCMAKE_TOOLCHAIN_FILE=$(DEVKITPRO)/cmake/Wii.cmake
	MAKEACTION := static
else ifeq ($(platform),wiiu)                    # wiiu-static
	CMAKEFLAGS_EXTRA := -DCMAKE_TOOLCHAIN_FILE=$(DEVKITPRO)/cmake/WiiU.cmake
	MAKEACTION := static
else ifeq ($(platform),libnx)                   # libnx-static
	CMAKEFLAGS_EXTRA := -DCMAKE_TOOLCHAIN_FILE=$(DEVKITPRO)/cmake/NintendoSwitch.cmake
	MAKEACTION := static
else ifeq ($(platform),emscripten)              # emscripten-static
	MAKEACTION := static
	CORESTATIC_SUFFIX := .bc
endif

.PHONY: default libretro

default: libretro

MAKEARGS = $(MAKEACTION) \
	COREFILE=$(COREFILE) COREDIR=. CORESTATIC=$(CORESTATIC)$(CORESTATIC_SUFFIX) \
	$(MAKEEXTRA) \
	CMAKEFLAGS_EXTRA="$(CMAKEFLAGS_EXTRA)"

libretro:
	$(MAKE) -f makefile zlib
	$(MAKE) -f makefile $(MAKEARGS)
