name: Ubuntu Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Files
        uses: actions/checkout@v3
      - name: Setup Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install make cmake gcc zlib1g-dev libsdl2-dev
      - name: Build hatariB
        run: make SO_SUFFIX=.so
      - name: Prepare Artifact
        run: |
            mkdir artifact
            mkdir artifact/cores
            cp build/*.so artifact/cores
            mkdir artifact/info
            cp info/*.* artifact/info
            echo "BUILD_TAG=$(git log -1 --format=\"%ad--%h\" --date=format-local:\"%Y-%m-%d-%H%M%S\")" >> $env:GITHUB_ENV
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: hatarib-${{ env.BUILD_TAG }}
          path: artifact/
