name: Win32 Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Files
        uses: actions/checkout@v3
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          install: make mingw-w64-i686-zlib mingw-w64-i686-gcc mingw-w64-i686-cmake mingw-w64-i686-SDL2
      - name: Build hatariB
        shell: msys2 {0}
        run: make
      - name: Prepare Artifact
        shell: pwsh
        run: |
            mkdir artifact
            mkdir artifact/cores
            copy build/*.dll artifact/cores
            mkdir artifact/info
            copy info/*.* artifact/info
            echo "BUILD_TAG=$(git log -1 --format="%ad--%h" --date=format-local:"%Y-%m-%d-%H%M%S")" >> $env:GITHUB_ENV
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: hatarib-win32-${{ env.BUILD_TAG }}
          path: artifact/
